### ISSUE TITLE
Create base file structure

### ISSUE THREAD

**Issue by fhsbatista** [fhsbatista/journal-flutter#1]

**Comment by fhsbatista** [comment]
a6b4b94dfb4156cc393a9afe79cd2ca217f10dc0

**Comment by fhsbatista** [comment]
Closed by mistake

**Comment by fiaz-ali** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
renwoox, @keyiiiii, @hustxiaoc, @LusciousLace, @ChinW, @andmironov, @cs-shares-guy, @liwtattbs2019, @alobanov, @CannonVegetable, @dladowitz, @jsonwen, @fonov, @cm112344, @rameerez, @Markshall, @imannaz, @scriptsman, @d4nyll, @BiswajitDtta, @chadsr, @chenleicrm, @Salamaleko, @alexej520, @Ciaran0, @lupelius, @wintermutt, @meoz, @mdcpepper, @Roosso, @onuryavuz, @rtzll, @ivanessence, @juno, @rys-acme, @Diversified1, @jccherry, @divizdev, @Pikachu2Github, @patie, @benjioh5, @stuartjk, @bchoubert, @daronjay, @alexinblock, @yannickboog, @dymissy, @orobogenius, @NeonSpork, @ajaykarwaldandevri, @StefanoGR, @xerod, @barnumbirr, @mac-s-g, @trubel, @CoxxA, @AlvisBrown, @danny-englander, @firede, @jfrausto, @quanack, @ryanpcmcquen, @csaper, @kimtaejin3, @FiberJW, @arden, @CapitanRedBeard, @lexybarton, @eznix86, @mcpeng, @therealwolf42, @daffavcd, @drondov, @leakeyqq, @mr-bloom, @burnaDLX, @noctifer20, @nearontheinside, @MrCSharp22, @dongabrielli, @krocon, @ik5, @ankitm27, @Jannchie, @afarukcali, @pengpengliu, @rashad, @romejiang, @ElRakabawi, @mdjordjevic, @wmira, @spences10, @jhrr, @mattiaerre, @apski, @superdcc, @VJELO, @pramodpalutla, @t32k
